version: '3.8'
services:

  spring:
    image: app:0.0.1
    container_name: spring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - db
      - rabbit-mq
    environment: 
      - SPRING_DATASOURCE_URL= r2dbc:postgresql://db/fusiondb

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: fusiondb
      POSTGRES_USER: egor
      POSTGRES_PASSWORD: fusion
    ports:
      - "5433:5432"    

  rabbit-mq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_USER: egor
      RABBITMQ_PASS: fusion
    ports:
      - 5672:5672
      - 15672:15672
    

    # volumes:
    #   - /home/fusion/works/billing-job/src/sql/:/mnt/:rw

# version: '3.8'
# services:
#   db:
#     image: postgres
#     container_name: postgres
#     environment:
#       POSTGRES_DB: fusiondb
#       POSTGRES_USER: egor
#       POSTGRES_PASSWORD: fusion
#     ports:
#       - "5433:5432"
#     volumes:
#       - /home/fusion/works/billing-job/src/sql/:/mnt/:rw

# version: '3.1'
# services:
#   db:
#     image: mysql
#     environment:
#       MYSQL_DATABASE: fusiondb
#       MYSQL_USER: egor
#       MYSQL_PASSWORD: fusion
#       MYSQL_ROOT_PASSWORD: fusion
#     ports:
#       - "3307:3306"