server:
  port: 8083

spring:
  config:
    activate:
      on-profile: prod
  flyway:
    enabled: true
    url: jdbc:postgresql://db/fusiondb
    user: egor
    password: fusion
    locations: classpath:db/migration
#    baselineOnMigrate: true
    logging: true
  r2dbc:
#    url: ${DB_NAME}
#    user: ${DB_USER}
#    password: ${DB_PASSWORD}
    url: r2dbc:postgresql://db/fusiondb
    username: egor
    password: fusion
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: egor
    password: fusion

logging:
  level:
    org:
      springframework:
        security: debug

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iterations: 64
      keyLength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: petapp
