
server:
  port: 8084

spring:
  config:
    activate:
      on-profile: dev
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/fusiondb
    user: egor
    password: fusion
    locations: classpath:db/migration
    #    baselineOnMigrate: true
    logging: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/fusiondb
    username: egor
    password: fusion
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: egor
    password: fusion

logging:
  level:
#    org.springframework.security: DEBUG
    reactor.netty.http.client.HttpClient: DEBUG

#logging:
#  level:
#    org:
#      springframework:
#        security: debug
#
##logging:
##  level:
##    reactor:
##      netty:
##        http:
##          client:
##            HttpClient=DEBUG:

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iterations: 64
      keyLength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: petapp


